package docgen

import (
	"fmt"
	"strings"

	"github.com/Lyra-Language/lyra/pkg/ast"
)

// Heading depths. A module page is one document with the module as its title, so a
// declaration is an h3 under its kind's h2, and a doc comment's own headings are shifted
// to sit below whatever they are nested under.
const (
	kindHeadingLevel = 2
	declHeadingLevel = 3
	memberListLevel  = 4
)

// RenderMarkdown renders one module as a Markdown page with Starlight frontmatter.
//
// Starlight is the site this feeds (`lyra-website`), and its frontmatter needs a `title`
// and takes an optional `description`. Both are emitted as **quoted YAML scalars** —
// a module summary can contain a colon, which unquoted would make the frontmatter parse
// as a nested mapping or fail outright, and that failure surfaces as a broken build in
// another repository rather than as an error here.
func RenderMarkdown(m Module) []byte {
	var b strings.Builder

	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %s\n", yamlString(m.Path))
	if m.Doc != nil && m.Doc.Summary != "" {
		fmt.Fprintf(&b, "description: %s\n", yamlString(m.Doc.Summary))
	}
	b.WriteString("---\n\n")

	b.WriteString(generatedNotice)

	if m.Doc != nil {
		// The module's own documentation is the page's lead, so its headings sit
		// under the page title: one level down.
		b.WriteString(renderBody(m.Doc.Text, 1))
		b.WriteString("\n\n")
	}

	if len(m.Decls) == 0 {
		b.WriteString("This module exports nothing.\n")
		return []byte(b.String())
	}

	for _, s := range pageSections(m) {
		fmt.Fprintf(&b, "%s %s\n\n", strings.Repeat("#", kindHeadingLevel), s.heading)
		for _, d := range s.decls {
			// Each declaration is normalized to end in exactly one blank line, so
			// the spacing before the next heading does not depend on whether the
			// last thing rendered was prose, a tight member list or a code fence.
			// Markdown needs that blank line: a heading butted against a list is
			// parsed as part of the list by some renderers.
			var rendered strings.Builder
			renderDecl(&rendered, d)
			b.WriteString(strings.TrimRight(rendered.String(), "\n"))
			b.WriteString("\n\n")
		}
	}
	return []byte(b.String())
}

// section is one h2 on the page.
type section struct {
	heading string
	decls   []Decl
}

// pageSections is the page's running order.
//
// Types and traits first — a reader needs the vocabulary before the operations — then the
// free functions and the methods grouped by receiver, which is where most of a module
// lives. Values are rare, and **implementations go last**.
//
// Trailing the impls is not tidiness. `std/prelude/math.lyra` alone contributes 78 of
// them (`Add for i8`, `Add for i16`, …), so anywhere earlier they are a wall between the
// traits and the part of the page anyone reads, and the sidebar's table of contents
// becomes a list of arithmetic instantiations with the module's actual surface below the
// fold. They are also the section least often *looked up*: an impl is what makes `+` work
// on a type, and a reader who wants that consults the trait or the operator, not a
// hundred one-line entries.
//
// **The methods are grouped by their `self` type rather than listed alphabetically**, and
// that follows the language: with UFCS there is no separate method declaration, so `self`
// is the only thing that says `trim` belongs to `string`. One flat run of seventy
// functions therefore hides which type each is for — exactly the fact a reader is looking
// for — while these groupings reassemble it. It also makes the sidebar's table of
// contents an index of the module's types.
func pageSections(m Module) []section {
	rest, free, groups := m.Partition()

	var out []section
	add := func(heading string, decls []Decl) {
		if len(decls) > 0 {
			out = append(out, section{heading, decls})
		}
	}

	add(KindType.String(), declsOfKind(rest, KindType))
	add(KindTrait.String(), declsOfKind(rest, KindTrait))
	// "Functions" keeps its plain name: with the methods under their receivers, what is
	// left here *is* the module's free functions — constructors and ambient helpers.
	add("Functions", free)
	for _, g := range groups {
		add("Methods on `"+g.Receiver+"`", g.Decls)
	}
	add(KindValue.String(), declsOfKind(rest, KindValue))
	add(KindImpl.String(), declsOfKind(rest, KindImpl))
	return out
}

const generatedNotice = "<!-- Generated by `lyrac doc`. Edit the `///` comments in the source, not this file. -->\n\n"

func declsOfKind(decls []Decl, kind Kind) []Decl {
	var out []Decl
	for _, d := range decls {
		if d.Kind == kind {
			out = append(out, d)
		}
	}
	return out
}

func renderDecl(b *strings.Builder, d Decl) {
	fmt.Fprintf(b, "%s `%s`\n\n", strings.Repeat("#", declHeadingLevel), d.Name)
	fmt.Fprintf(b, "```lyra\n%s\n```\n\n", d.Signature)

	if d.Doc != nil {
		// Shifted past the declaration's own heading, so a doc's `# Panics` becomes
		// an h4 inside the page instead of an h1 in the middle of it.
		b.WriteString(renderBody(d.Doc.Text, declHeadingLevel))
		b.WriteString("\n\n")
	}

	if len(d.Members) > 0 {
		fmt.Fprintf(b, "%s %s\n\n", strings.Repeat("#", memberListLevel), memberHeading(d.Kind))
		for _, mem := range d.Members {
			renderMember(b, mem)
		}
	}
}

// memberHeading names what a declaration's members are, which differs by kind — a
// struct has fields, a data type has constructors, a trait and an impl have methods.
func memberHeading(kind Kind) string {
	switch kind {
	case KindTrait, KindImpl:
		return "Methods"
	default:
		return "Members"
	}
}

// renderMember prints a member as a definition-style list item: the signature in code,
// then its prose indented under it so a multi-paragraph member doc stays inside the
// item rather than ending the list.
func renderMember(b *strings.Builder, m Member) {
	fmt.Fprintf(b, "- `%s`", m.Signature)
	if m.Doc == nil {
		b.WriteString("\n")
		return
	}
	summary, rest := splitLead(m.Doc.Text)
	fmt.Fprintf(b, " — %s\n", summary)
	if rest == "" {
		// No trailing blank line: a tight list reads as one block, which is what a
		// list of one-line member descriptions should look like.
		return
	}
	// Two spaces of indent continue the list item in Markdown; without it a second
	// paragraph closes the list and reads as body text belonging to the declaration
	// rather than to the member.
	b.WriteString("\n" + indent(renderBody(rest, memberListLevel), "  ") + "\n\n")
}

// renderBody prepares a doc comment body for embedding in a page at the given heading
// depth: headings shifted so they nest under what contains them, and bare fences tagged
// as Lyra.
func renderBody(text string, depth int) string {
	return ast.TagBareFences(ast.ShiftHeadings(text, depth), "lyra")
}

// splitLead divides a doc body into its first paragraph and everything after, with the
// first paragraph flattened onto one line so it can follow an em dash on the list item.
func splitLead(text string) (lead, rest string) {
	paras := strings.SplitN(strings.TrimSpace(text), "\n\n", 2)
	lead = strings.Join(strings.Fields(paras[0]), " ")
	if len(paras) > 1 {
		rest = strings.TrimSpace(paras[1])
	}
	return lead, rest
}

func indent(text, prefix string) string {
	lines := strings.Split(text, "\n")
	for i, l := range lines {
		if strings.TrimSpace(l) == "" {
			continue
		}
		lines[i] = prefix + l
	}
	return strings.Join(lines, "\n")
}

// yamlString quotes a scalar for YAML frontmatter. Double quotes with the two escapes
// YAML's double-quoted style requires, which is enough for prose and is the style that
// can hold a colon, a `#`, or a leading `-` without changing meaning.
func yamlString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	// A newline in a summary would end the frontmatter line; summaries are already
	// flattened, but a value arriving from elsewhere must not be able to break out.
	s = strings.ReplaceAll(s, "\n", " ")
	return `"` + s + `"`
}

// FileName is the page a module writes to: `std.prelude` becomes `std-prelude.md`.
//
// Flat rather than nested (`std/prelude.md`), because a module is a leaf in the docs
// even when it is a directory in the source — `std.prelude` is one page, and nesting
// would put it under a `std` that documents nothing.
//
// **Dashes rather than dots**, which is not cosmetic: a static-site generator derives a
// URL slug from the file name, and dots are stripped rather than preserved — Starlight
// turns `std.prelude.md` into `/reference/stdprelude/`. The page's own title is still
// the real dotted path, so the module name is never in doubt on the page itself; this
// only decides what the address looks like.
func FileName(modulePath string) string {
	if modulePath == "" {
		// The entry file of a single-file program declares no module. It still has
		// a page, and "main" is what it is.
		return "main.md"
	}
	return strings.ReplaceAll(modulePath, ".", "-") + ".md"
}
