// Generated by `gen/gen.lyra` from dear_bindings' `dcimgui.json` — do not edit; rerun
// the generator instead. One C accessor per field of the structs in FIELD_STRUCTS, since
// Lyra cannot reach a C struct's field without its layout.

#include "imgui.h"

extern "C" {

float lyra_imgui_ImGuiStyle_get_FontSizeBase(ImGuiStyle* self) { return self->FontSizeBase; }
void lyra_imgui_ImGuiStyle_set_FontSizeBase(ImGuiStyle* self, float value) { self->FontSizeBase = value; }
float lyra_imgui_ImGuiStyle_get_FontScaleMain(ImGuiStyle* self) { return self->FontScaleMain; }
void lyra_imgui_ImGuiStyle_set_FontScaleMain(ImGuiStyle* self, float value) { self->FontScaleMain = value; }
float lyra_imgui_ImGuiStyle_get_FontScaleDpi(ImGuiStyle* self) { return self->FontScaleDpi; }
void lyra_imgui_ImGuiStyle_set_FontScaleDpi(ImGuiStyle* self, float value) { self->FontScaleDpi = value; }
float lyra_imgui_ImGuiStyle_get_Alpha(ImGuiStyle* self) { return self->Alpha; }
void lyra_imgui_ImGuiStyle_set_Alpha(ImGuiStyle* self, float value) { self->Alpha = value; }
float lyra_imgui_ImGuiStyle_get_DisabledAlpha(ImGuiStyle* self) { return self->DisabledAlpha; }
void lyra_imgui_ImGuiStyle_set_DisabledAlpha(ImGuiStyle* self, float value) { self->DisabledAlpha = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_WindowPadding(ImGuiStyle* self) { return self->WindowPadding; }
void lyra_imgui_ImGuiStyle_set_WindowPadding(ImGuiStyle* self, ImVec2 value) { self->WindowPadding = value; }
float lyra_imgui_ImGuiStyle_get_WindowRounding(ImGuiStyle* self) { return self->WindowRounding; }
void lyra_imgui_ImGuiStyle_set_WindowRounding(ImGuiStyle* self, float value) { self->WindowRounding = value; }
float lyra_imgui_ImGuiStyle_get_WindowBorderSize(ImGuiStyle* self) { return self->WindowBorderSize; }
void lyra_imgui_ImGuiStyle_set_WindowBorderSize(ImGuiStyle* self, float value) { self->WindowBorderSize = value; }
float lyra_imgui_ImGuiStyle_get_WindowBorderHoverPadding(ImGuiStyle* self) { return self->WindowBorderHoverPadding; }
void lyra_imgui_ImGuiStyle_set_WindowBorderHoverPadding(ImGuiStyle* self, float value) { self->WindowBorderHoverPadding = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_WindowMinSize(ImGuiStyle* self) { return self->WindowMinSize; }
void lyra_imgui_ImGuiStyle_set_WindowMinSize(ImGuiStyle* self, ImVec2 value) { self->WindowMinSize = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_WindowTitleAlign(ImGuiStyle* self) { return self->WindowTitleAlign; }
void lyra_imgui_ImGuiStyle_set_WindowTitleAlign(ImGuiStyle* self, ImVec2 value) { self->WindowTitleAlign = value; }
ImGuiDir lyra_imgui_ImGuiStyle_get_WindowMenuButtonPosition(ImGuiStyle* self) { return self->WindowMenuButtonPosition; }
void lyra_imgui_ImGuiStyle_set_WindowMenuButtonPosition(ImGuiStyle* self, ImGuiDir value) { self->WindowMenuButtonPosition = value; }
float lyra_imgui_ImGuiStyle_get_ChildRounding(ImGuiStyle* self) { return self->ChildRounding; }
void lyra_imgui_ImGuiStyle_set_ChildRounding(ImGuiStyle* self, float value) { self->ChildRounding = value; }
float lyra_imgui_ImGuiStyle_get_ChildBorderSize(ImGuiStyle* self) { return self->ChildBorderSize; }
void lyra_imgui_ImGuiStyle_set_ChildBorderSize(ImGuiStyle* self, float value) { self->ChildBorderSize = value; }
float lyra_imgui_ImGuiStyle_get_PopupRounding(ImGuiStyle* self) { return self->PopupRounding; }
void lyra_imgui_ImGuiStyle_set_PopupRounding(ImGuiStyle* self, float value) { self->PopupRounding = value; }
float lyra_imgui_ImGuiStyle_get_PopupBorderSize(ImGuiStyle* self) { return self->PopupBorderSize; }
void lyra_imgui_ImGuiStyle_set_PopupBorderSize(ImGuiStyle* self, float value) { self->PopupBorderSize = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_FramePadding(ImGuiStyle* self) { return self->FramePadding; }
void lyra_imgui_ImGuiStyle_set_FramePadding(ImGuiStyle* self, ImVec2 value) { self->FramePadding = value; }
float lyra_imgui_ImGuiStyle_get_FrameRounding(ImGuiStyle* self) { return self->FrameRounding; }
void lyra_imgui_ImGuiStyle_set_FrameRounding(ImGuiStyle* self, float value) { self->FrameRounding = value; }
float lyra_imgui_ImGuiStyle_get_FrameBorderSize(ImGuiStyle* self) { return self->FrameBorderSize; }
void lyra_imgui_ImGuiStyle_set_FrameBorderSize(ImGuiStyle* self, float value) { self->FrameBorderSize = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_ItemSpacing(ImGuiStyle* self) { return self->ItemSpacing; }
void lyra_imgui_ImGuiStyle_set_ItemSpacing(ImGuiStyle* self, ImVec2 value) { self->ItemSpacing = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_ItemInnerSpacing(ImGuiStyle* self) { return self->ItemInnerSpacing; }
void lyra_imgui_ImGuiStyle_set_ItemInnerSpacing(ImGuiStyle* self, ImVec2 value) { self->ItemInnerSpacing = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_CellPadding(ImGuiStyle* self) { return self->CellPadding; }
void lyra_imgui_ImGuiStyle_set_CellPadding(ImGuiStyle* self, ImVec2 value) { self->CellPadding = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_TouchExtraPadding(ImGuiStyle* self) { return self->TouchExtraPadding; }
void lyra_imgui_ImGuiStyle_set_TouchExtraPadding(ImGuiStyle* self, ImVec2 value) { self->TouchExtraPadding = value; }
float lyra_imgui_ImGuiStyle_get_IndentSpacing(ImGuiStyle* self) { return self->IndentSpacing; }
void lyra_imgui_ImGuiStyle_set_IndentSpacing(ImGuiStyle* self, float value) { self->IndentSpacing = value; }
float lyra_imgui_ImGuiStyle_get_ColumnsMinSpacing(ImGuiStyle* self) { return self->ColumnsMinSpacing; }
void lyra_imgui_ImGuiStyle_set_ColumnsMinSpacing(ImGuiStyle* self, float value) { self->ColumnsMinSpacing = value; }
float lyra_imgui_ImGuiStyle_get_ScrollbarSize(ImGuiStyle* self) { return self->ScrollbarSize; }
void lyra_imgui_ImGuiStyle_set_ScrollbarSize(ImGuiStyle* self, float value) { self->ScrollbarSize = value; }
float lyra_imgui_ImGuiStyle_get_ScrollbarRounding(ImGuiStyle* self) { return self->ScrollbarRounding; }
void lyra_imgui_ImGuiStyle_set_ScrollbarRounding(ImGuiStyle* self, float value) { self->ScrollbarRounding = value; }
float lyra_imgui_ImGuiStyle_get_ScrollbarPadding(ImGuiStyle* self) { return self->ScrollbarPadding; }
void lyra_imgui_ImGuiStyle_set_ScrollbarPadding(ImGuiStyle* self, float value) { self->ScrollbarPadding = value; }
float lyra_imgui_ImGuiStyle_get_GrabMinSize(ImGuiStyle* self) { return self->GrabMinSize; }
void lyra_imgui_ImGuiStyle_set_GrabMinSize(ImGuiStyle* self, float value) { self->GrabMinSize = value; }
float lyra_imgui_ImGuiStyle_get_GrabRounding(ImGuiStyle* self) { return self->GrabRounding; }
void lyra_imgui_ImGuiStyle_set_GrabRounding(ImGuiStyle* self, float value) { self->GrabRounding = value; }
float lyra_imgui_ImGuiStyle_get_LogSliderDeadzone(ImGuiStyle* self) { return self->LogSliderDeadzone; }
void lyra_imgui_ImGuiStyle_set_LogSliderDeadzone(ImGuiStyle* self, float value) { self->LogSliderDeadzone = value; }
float lyra_imgui_ImGuiStyle_get_ImageRounding(ImGuiStyle* self) { return self->ImageRounding; }
void lyra_imgui_ImGuiStyle_set_ImageRounding(ImGuiStyle* self, float value) { self->ImageRounding = value; }
float lyra_imgui_ImGuiStyle_get_ImageBorderSize(ImGuiStyle* self) { return self->ImageBorderSize; }
void lyra_imgui_ImGuiStyle_set_ImageBorderSize(ImGuiStyle* self, float value) { self->ImageBorderSize = value; }
float lyra_imgui_ImGuiStyle_get_TabRounding(ImGuiStyle* self) { return self->TabRounding; }
void lyra_imgui_ImGuiStyle_set_TabRounding(ImGuiStyle* self, float value) { self->TabRounding = value; }
float lyra_imgui_ImGuiStyle_get_TabBorderSize(ImGuiStyle* self) { return self->TabBorderSize; }
void lyra_imgui_ImGuiStyle_set_TabBorderSize(ImGuiStyle* self, float value) { self->TabBorderSize = value; }
float lyra_imgui_ImGuiStyle_get_TabMinWidthBase(ImGuiStyle* self) { return self->TabMinWidthBase; }
void lyra_imgui_ImGuiStyle_set_TabMinWidthBase(ImGuiStyle* self, float value) { self->TabMinWidthBase = value; }
float lyra_imgui_ImGuiStyle_get_TabMinWidthShrink(ImGuiStyle* self) { return self->TabMinWidthShrink; }
void lyra_imgui_ImGuiStyle_set_TabMinWidthShrink(ImGuiStyle* self, float value) { self->TabMinWidthShrink = value; }
float lyra_imgui_ImGuiStyle_get_TabCloseButtonMinWidthSelected(ImGuiStyle* self) { return self->TabCloseButtonMinWidthSelected; }
void lyra_imgui_ImGuiStyle_set_TabCloseButtonMinWidthSelected(ImGuiStyle* self, float value) { self->TabCloseButtonMinWidthSelected = value; }
float lyra_imgui_ImGuiStyle_get_TabCloseButtonMinWidthUnselected(ImGuiStyle* self) { return self->TabCloseButtonMinWidthUnselected; }
void lyra_imgui_ImGuiStyle_set_TabCloseButtonMinWidthUnselected(ImGuiStyle* self, float value) { self->TabCloseButtonMinWidthUnselected = value; }
float lyra_imgui_ImGuiStyle_get_TabBarBorderSize(ImGuiStyle* self) { return self->TabBarBorderSize; }
void lyra_imgui_ImGuiStyle_set_TabBarBorderSize(ImGuiStyle* self, float value) { self->TabBarBorderSize = value; }
float lyra_imgui_ImGuiStyle_get_TabBarOverlineSize(ImGuiStyle* self) { return self->TabBarOverlineSize; }
void lyra_imgui_ImGuiStyle_set_TabBarOverlineSize(ImGuiStyle* self, float value) { self->TabBarOverlineSize = value; }
float lyra_imgui_ImGuiStyle_get_TableAngledHeadersAngle(ImGuiStyle* self) { return self->TableAngledHeadersAngle; }
void lyra_imgui_ImGuiStyle_set_TableAngledHeadersAngle(ImGuiStyle* self, float value) { self->TableAngledHeadersAngle = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_TableAngledHeadersTextAlign(ImGuiStyle* self) { return self->TableAngledHeadersTextAlign; }
void lyra_imgui_ImGuiStyle_set_TableAngledHeadersTextAlign(ImGuiStyle* self, ImVec2 value) { self->TableAngledHeadersTextAlign = value; }
ImGuiTreeNodeFlags lyra_imgui_ImGuiStyle_get_TreeLinesFlags(ImGuiStyle* self) { return self->TreeLinesFlags; }
void lyra_imgui_ImGuiStyle_set_TreeLinesFlags(ImGuiStyle* self, ImGuiTreeNodeFlags value) { self->TreeLinesFlags = value; }
float lyra_imgui_ImGuiStyle_get_TreeLinesSize(ImGuiStyle* self) { return self->TreeLinesSize; }
void lyra_imgui_ImGuiStyle_set_TreeLinesSize(ImGuiStyle* self, float value) { self->TreeLinesSize = value; }
float lyra_imgui_ImGuiStyle_get_TreeLinesRounding(ImGuiStyle* self) { return self->TreeLinesRounding; }
void lyra_imgui_ImGuiStyle_set_TreeLinesRounding(ImGuiStyle* self, float value) { self->TreeLinesRounding = value; }
float lyra_imgui_ImGuiStyle_get_MenuItemRounding(ImGuiStyle* self) { return self->MenuItemRounding; }
void lyra_imgui_ImGuiStyle_set_MenuItemRounding(ImGuiStyle* self, float value) { self->MenuItemRounding = value; }
float lyra_imgui_ImGuiStyle_get_SelectableRounding(ImGuiStyle* self) { return self->SelectableRounding; }
void lyra_imgui_ImGuiStyle_set_SelectableRounding(ImGuiStyle* self, float value) { self->SelectableRounding = value; }
float lyra_imgui_ImGuiStyle_get_DragDropTargetRounding(ImGuiStyle* self) { return self->DragDropTargetRounding; }
void lyra_imgui_ImGuiStyle_set_DragDropTargetRounding(ImGuiStyle* self, float value) { self->DragDropTargetRounding = value; }
float lyra_imgui_ImGuiStyle_get_DragDropTargetBorderSize(ImGuiStyle* self) { return self->DragDropTargetBorderSize; }
void lyra_imgui_ImGuiStyle_set_DragDropTargetBorderSize(ImGuiStyle* self, float value) { self->DragDropTargetBorderSize = value; }
float lyra_imgui_ImGuiStyle_get_DragDropTargetPadding(ImGuiStyle* self) { return self->DragDropTargetPadding; }
void lyra_imgui_ImGuiStyle_set_DragDropTargetPadding(ImGuiStyle* self, float value) { self->DragDropTargetPadding = value; }
float lyra_imgui_ImGuiStyle_get_ColorMarkerSize(ImGuiStyle* self) { return self->ColorMarkerSize; }
void lyra_imgui_ImGuiStyle_set_ColorMarkerSize(ImGuiStyle* self, float value) { self->ColorMarkerSize = value; }
ImGuiDir lyra_imgui_ImGuiStyle_get_ColorButtonPosition(ImGuiStyle* self) { return self->ColorButtonPosition; }
void lyra_imgui_ImGuiStyle_set_ColorButtonPosition(ImGuiStyle* self, ImGuiDir value) { self->ColorButtonPosition = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_ButtonTextAlign(ImGuiStyle* self) { return self->ButtonTextAlign; }
void lyra_imgui_ImGuiStyle_set_ButtonTextAlign(ImGuiStyle* self, ImVec2 value) { self->ButtonTextAlign = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_SelectableTextAlign(ImGuiStyle* self) { return self->SelectableTextAlign; }
void lyra_imgui_ImGuiStyle_set_SelectableTextAlign(ImGuiStyle* self, ImVec2 value) { self->SelectableTextAlign = value; }
float lyra_imgui_ImGuiStyle_get_InputTextCursorSize(ImGuiStyle* self) { return self->InputTextCursorSize; }
void lyra_imgui_ImGuiStyle_set_InputTextCursorSize(ImGuiStyle* self, float value) { self->InputTextCursorSize = value; }
float lyra_imgui_ImGuiStyle_get_SeparatorSize(ImGuiStyle* self) { return self->SeparatorSize; }
void lyra_imgui_ImGuiStyle_set_SeparatorSize(ImGuiStyle* self, float value) { self->SeparatorSize = value; }
float lyra_imgui_ImGuiStyle_get_SeparatorTextBorderSize(ImGuiStyle* self) { return self->SeparatorTextBorderSize; }
void lyra_imgui_ImGuiStyle_set_SeparatorTextBorderSize(ImGuiStyle* self, float value) { self->SeparatorTextBorderSize = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_SeparatorTextAlign(ImGuiStyle* self) { return self->SeparatorTextAlign; }
void lyra_imgui_ImGuiStyle_set_SeparatorTextAlign(ImGuiStyle* self, ImVec2 value) { self->SeparatorTextAlign = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_SeparatorTextPadding(ImGuiStyle* self) { return self->SeparatorTextPadding; }
void lyra_imgui_ImGuiStyle_set_SeparatorTextPadding(ImGuiStyle* self, ImVec2 value) { self->SeparatorTextPadding = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_DisplayWindowPadding(ImGuiStyle* self) { return self->DisplayWindowPadding; }
void lyra_imgui_ImGuiStyle_set_DisplayWindowPadding(ImGuiStyle* self, ImVec2 value) { self->DisplayWindowPadding = value; }
ImVec2 lyra_imgui_ImGuiStyle_get_DisplaySafeAreaPadding(ImGuiStyle* self) { return self->DisplaySafeAreaPadding; }
void lyra_imgui_ImGuiStyle_set_DisplaySafeAreaPadding(ImGuiStyle* self, ImVec2 value) { self->DisplaySafeAreaPadding = value; }
bool lyra_imgui_ImGuiStyle_get_DockingNodeHasCloseButton(ImGuiStyle* self) { return self->DockingNodeHasCloseButton; }
void lyra_imgui_ImGuiStyle_set_DockingNodeHasCloseButton(ImGuiStyle* self, bool value) { self->DockingNodeHasCloseButton = value; }
float lyra_imgui_ImGuiStyle_get_DockingSeparatorSize(ImGuiStyle* self) { return self->DockingSeparatorSize; }
void lyra_imgui_ImGuiStyle_set_DockingSeparatorSize(ImGuiStyle* self, float value) { self->DockingSeparatorSize = value; }
float lyra_imgui_ImGuiStyle_get_MouseCursorScale(ImGuiStyle* self) { return self->MouseCursorScale; }
void lyra_imgui_ImGuiStyle_set_MouseCursorScale(ImGuiStyle* self, float value) { self->MouseCursorScale = value; }
bool lyra_imgui_ImGuiStyle_get_AntiAliasedLines(ImGuiStyle* self) { return self->AntiAliasedLines; }
void lyra_imgui_ImGuiStyle_set_AntiAliasedLines(ImGuiStyle* self, bool value) { self->AntiAliasedLines = value; }
bool lyra_imgui_ImGuiStyle_get_AntiAliasedLinesUseTex(ImGuiStyle* self) { return self->AntiAliasedLinesUseTex; }
void lyra_imgui_ImGuiStyle_set_AntiAliasedLinesUseTex(ImGuiStyle* self, bool value) { self->AntiAliasedLinesUseTex = value; }
bool lyra_imgui_ImGuiStyle_get_AntiAliasedFill(ImGuiStyle* self) { return self->AntiAliasedFill; }
void lyra_imgui_ImGuiStyle_set_AntiAliasedFill(ImGuiStyle* self, bool value) { self->AntiAliasedFill = value; }
float lyra_imgui_ImGuiStyle_get_CurveTessellationTol(ImGuiStyle* self) { return self->CurveTessellationTol; }
void lyra_imgui_ImGuiStyle_set_CurveTessellationTol(ImGuiStyle* self, float value) { self->CurveTessellationTol = value; }
float lyra_imgui_ImGuiStyle_get_CircleTessellationMaxError(ImGuiStyle* self) { return self->CircleTessellationMaxError; }
void lyra_imgui_ImGuiStyle_set_CircleTessellationMaxError(ImGuiStyle* self, float value) { self->CircleTessellationMaxError = value; }
ImVec4 lyra_imgui_ImGuiStyle_get_Colors(ImGuiStyle* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->Colors) ? self->Colors[index] : ImVec4(); }
void lyra_imgui_ImGuiStyle_set_Colors(ImGuiStyle* self, int index, ImVec4 value) { if (index >= 0 && index < IM_ARRAYSIZE(self->Colors)) self->Colors[index] = value; }
float lyra_imgui_ImGuiStyle_get_HoverStationaryDelay(ImGuiStyle* self) { return self->HoverStationaryDelay; }
void lyra_imgui_ImGuiStyle_set_HoverStationaryDelay(ImGuiStyle* self, float value) { self->HoverStationaryDelay = value; }
float lyra_imgui_ImGuiStyle_get_HoverDelayShort(ImGuiStyle* self) { return self->HoverDelayShort; }
void lyra_imgui_ImGuiStyle_set_HoverDelayShort(ImGuiStyle* self, float value) { self->HoverDelayShort = value; }
float lyra_imgui_ImGuiStyle_get_HoverDelayNormal(ImGuiStyle* self) { return self->HoverDelayNormal; }
void lyra_imgui_ImGuiStyle_set_HoverDelayNormal(ImGuiStyle* self, float value) { self->HoverDelayNormal = value; }
ImGuiHoveredFlags lyra_imgui_ImGuiStyle_get_HoverFlagsForTooltipMouse(ImGuiStyle* self) { return self->HoverFlagsForTooltipMouse; }
void lyra_imgui_ImGuiStyle_set_HoverFlagsForTooltipMouse(ImGuiStyle* self, ImGuiHoveredFlags value) { self->HoverFlagsForTooltipMouse = value; }
ImGuiHoveredFlags lyra_imgui_ImGuiStyle_get_HoverFlagsForTooltipNav(ImGuiStyle* self) { return self->HoverFlagsForTooltipNav; }
void lyra_imgui_ImGuiStyle_set_HoverFlagsForTooltipNav(ImGuiStyle* self, ImGuiHoveredFlags value) { self->HoverFlagsForTooltipNav = value; }
ImGuiConfigFlags lyra_imgui_ImGuiIO_get_ConfigFlags(ImGuiIO* self) { return self->ConfigFlags; }
void lyra_imgui_ImGuiIO_set_ConfigFlags(ImGuiIO* self, ImGuiConfigFlags value) { self->ConfigFlags = value; }
ImGuiBackendFlags lyra_imgui_ImGuiIO_get_BackendFlags(ImGuiIO* self) { return self->BackendFlags; }
void lyra_imgui_ImGuiIO_set_BackendFlags(ImGuiIO* self, ImGuiBackendFlags value) { self->BackendFlags = value; }
ImVec2 lyra_imgui_ImGuiIO_get_DisplaySize(ImGuiIO* self) { return self->DisplaySize; }
void lyra_imgui_ImGuiIO_set_DisplaySize(ImGuiIO* self, ImVec2 value) { self->DisplaySize = value; }
ImVec2 lyra_imgui_ImGuiIO_get_DisplayFramebufferScale(ImGuiIO* self) { return self->DisplayFramebufferScale; }
void lyra_imgui_ImGuiIO_set_DisplayFramebufferScale(ImGuiIO* self, ImVec2 value) { self->DisplayFramebufferScale = value; }
float lyra_imgui_ImGuiIO_get_DeltaTime(ImGuiIO* self) { return self->DeltaTime; }
void lyra_imgui_ImGuiIO_set_DeltaTime(ImGuiIO* self, float value) { self->DeltaTime = value; }
float lyra_imgui_ImGuiIO_get_IniSavingRate(ImGuiIO* self) { return self->IniSavingRate; }
void lyra_imgui_ImGuiIO_set_IniSavingRate(ImGuiIO* self, float value) { self->IniSavingRate = value; }
const char* lyra_imgui_ImGuiIO_get_IniFilename(ImGuiIO* self) { return self->IniFilename; }
const char* lyra_imgui_ImGuiIO_get_LogFilename(ImGuiIO* self) { return self->LogFilename; }
ImFontAtlas* lyra_imgui_ImGuiIO_get_Fonts(ImGuiIO* self) { return self->Fonts; }
ImFont* lyra_imgui_ImGuiIO_get_FontDefault(ImGuiIO* self) { return self->FontDefault; }
bool lyra_imgui_ImGuiIO_get_FontAllowUserScaling(ImGuiIO* self) { return self->FontAllowUserScaling; }
void lyra_imgui_ImGuiIO_set_FontAllowUserScaling(ImGuiIO* self, bool value) { self->FontAllowUserScaling = value; }
bool lyra_imgui_ImGuiIO_get_ConfigNavSwapGamepadButtons(ImGuiIO* self) { return self->ConfigNavSwapGamepadButtons; }
void lyra_imgui_ImGuiIO_set_ConfigNavSwapGamepadButtons(ImGuiIO* self, bool value) { self->ConfigNavSwapGamepadButtons = value; }
bool lyra_imgui_ImGuiIO_get_ConfigNavMoveSetMousePos(ImGuiIO* self) { return self->ConfigNavMoveSetMousePos; }
void lyra_imgui_ImGuiIO_set_ConfigNavMoveSetMousePos(ImGuiIO* self, bool value) { self->ConfigNavMoveSetMousePos = value; }
bool lyra_imgui_ImGuiIO_get_ConfigNavCaptureKeyboard(ImGuiIO* self) { return self->ConfigNavCaptureKeyboard; }
void lyra_imgui_ImGuiIO_set_ConfigNavCaptureKeyboard(ImGuiIO* self, bool value) { self->ConfigNavCaptureKeyboard = value; }
bool lyra_imgui_ImGuiIO_get_ConfigNavEscapeClearFocusItem(ImGuiIO* self) { return self->ConfigNavEscapeClearFocusItem; }
void lyra_imgui_ImGuiIO_set_ConfigNavEscapeClearFocusItem(ImGuiIO* self, bool value) { self->ConfigNavEscapeClearFocusItem = value; }
bool lyra_imgui_ImGuiIO_get_ConfigNavEscapeClearFocusWindow(ImGuiIO* self) { return self->ConfigNavEscapeClearFocusWindow; }
void lyra_imgui_ImGuiIO_set_ConfigNavEscapeClearFocusWindow(ImGuiIO* self, bool value) { self->ConfigNavEscapeClearFocusWindow = value; }
bool lyra_imgui_ImGuiIO_get_ConfigNavCursorVisibleAuto(ImGuiIO* self) { return self->ConfigNavCursorVisibleAuto; }
void lyra_imgui_ImGuiIO_set_ConfigNavCursorVisibleAuto(ImGuiIO* self, bool value) { self->ConfigNavCursorVisibleAuto = value; }
bool lyra_imgui_ImGuiIO_get_ConfigNavCursorVisibleAlways(ImGuiIO* self) { return self->ConfigNavCursorVisibleAlways; }
void lyra_imgui_ImGuiIO_set_ConfigNavCursorVisibleAlways(ImGuiIO* self, bool value) { self->ConfigNavCursorVisibleAlways = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDockingNoSplit(ImGuiIO* self) { return self->ConfigDockingNoSplit; }
void lyra_imgui_ImGuiIO_set_ConfigDockingNoSplit(ImGuiIO* self, bool value) { self->ConfigDockingNoSplit = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDockingNoDockingOver(ImGuiIO* self) { return self->ConfigDockingNoDockingOver; }
void lyra_imgui_ImGuiIO_set_ConfigDockingNoDockingOver(ImGuiIO* self, bool value) { self->ConfigDockingNoDockingOver = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDockingWithShift(ImGuiIO* self) { return self->ConfigDockingWithShift; }
void lyra_imgui_ImGuiIO_set_ConfigDockingWithShift(ImGuiIO* self, bool value) { self->ConfigDockingWithShift = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDockingAlwaysTabBar(ImGuiIO* self) { return self->ConfigDockingAlwaysTabBar; }
void lyra_imgui_ImGuiIO_set_ConfigDockingAlwaysTabBar(ImGuiIO* self, bool value) { self->ConfigDockingAlwaysTabBar = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDockingTransparentPayload(ImGuiIO* self) { return self->ConfigDockingTransparentPayload; }
void lyra_imgui_ImGuiIO_set_ConfigDockingTransparentPayload(ImGuiIO* self, bool value) { self->ConfigDockingTransparentPayload = value; }
bool lyra_imgui_ImGuiIO_get_ConfigViewportsNoAutoMerge(ImGuiIO* self) { return self->ConfigViewportsNoAutoMerge; }
void lyra_imgui_ImGuiIO_set_ConfigViewportsNoAutoMerge(ImGuiIO* self, bool value) { self->ConfigViewportsNoAutoMerge = value; }
bool lyra_imgui_ImGuiIO_get_ConfigViewportsNoTaskBarIcon(ImGuiIO* self) { return self->ConfigViewportsNoTaskBarIcon; }
void lyra_imgui_ImGuiIO_set_ConfigViewportsNoTaskBarIcon(ImGuiIO* self, bool value) { self->ConfigViewportsNoTaskBarIcon = value; }
bool lyra_imgui_ImGuiIO_get_ConfigViewportsNoDecoration(ImGuiIO* self) { return self->ConfigViewportsNoDecoration; }
void lyra_imgui_ImGuiIO_set_ConfigViewportsNoDecoration(ImGuiIO* self, bool value) { self->ConfigViewportsNoDecoration = value; }
bool lyra_imgui_ImGuiIO_get_ConfigViewportsNoDefaultParent(ImGuiIO* self) { return self->ConfigViewportsNoDefaultParent; }
void lyra_imgui_ImGuiIO_set_ConfigViewportsNoDefaultParent(ImGuiIO* self, bool value) { self->ConfigViewportsNoDefaultParent = value; }
bool lyra_imgui_ImGuiIO_get_ConfigViewportsPlatformFocusSetsImGuiFocus(ImGuiIO* self) { return self->ConfigViewportsPlatformFocusSetsImGuiFocus; }
void lyra_imgui_ImGuiIO_set_ConfigViewportsPlatformFocusSetsImGuiFocus(ImGuiIO* self, bool value) { self->ConfigViewportsPlatformFocusSetsImGuiFocus = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDpiScaleFonts(ImGuiIO* self) { return self->ConfigDpiScaleFonts; }
void lyra_imgui_ImGuiIO_set_ConfigDpiScaleFonts(ImGuiIO* self, bool value) { self->ConfigDpiScaleFonts = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDpiScaleViewports(ImGuiIO* self) { return self->ConfigDpiScaleViewports; }
void lyra_imgui_ImGuiIO_set_ConfigDpiScaleViewports(ImGuiIO* self, bool value) { self->ConfigDpiScaleViewports = value; }
bool lyra_imgui_ImGuiIO_get_ConfigMacOSXBehaviors(ImGuiIO* self) { return self->ConfigMacOSXBehaviors; }
void lyra_imgui_ImGuiIO_set_ConfigMacOSXBehaviors(ImGuiIO* self, bool value) { self->ConfigMacOSXBehaviors = value; }
bool lyra_imgui_ImGuiIO_get_ConfigInputTrickleEventQueue(ImGuiIO* self) { return self->ConfigInputTrickleEventQueue; }
void lyra_imgui_ImGuiIO_set_ConfigInputTrickleEventQueue(ImGuiIO* self, bool value) { self->ConfigInputTrickleEventQueue = value; }
bool lyra_imgui_ImGuiIO_get_ConfigInputTextCursorBlink(ImGuiIO* self) { return self->ConfigInputTextCursorBlink; }
void lyra_imgui_ImGuiIO_set_ConfigInputTextCursorBlink(ImGuiIO* self, bool value) { self->ConfigInputTextCursorBlink = value; }
bool lyra_imgui_ImGuiIO_get_ConfigInputTextEnterKeepActive(ImGuiIO* self) { return self->ConfigInputTextEnterKeepActive; }
void lyra_imgui_ImGuiIO_set_ConfigInputTextEnterKeepActive(ImGuiIO* self, bool value) { self->ConfigInputTextEnterKeepActive = value; }
ImGuiColorEditFlags lyra_imgui_ImGuiIO_get_ConfigColorEditFlags(ImGuiIO* self) { return self->ConfigColorEditFlags; }
void lyra_imgui_ImGuiIO_set_ConfigColorEditFlags(ImGuiIO* self, ImGuiColorEditFlags value) { self->ConfigColorEditFlags = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDragClickToInputText(ImGuiIO* self) { return self->ConfigDragClickToInputText; }
void lyra_imgui_ImGuiIO_set_ConfigDragClickToInputText(ImGuiIO* self, bool value) { self->ConfigDragClickToInputText = value; }
bool lyra_imgui_ImGuiIO_get_ConfigWindowsResizeFromEdges(ImGuiIO* self) { return self->ConfigWindowsResizeFromEdges; }
void lyra_imgui_ImGuiIO_set_ConfigWindowsResizeFromEdges(ImGuiIO* self, bool value) { self->ConfigWindowsResizeFromEdges = value; }
bool lyra_imgui_ImGuiIO_get_ConfigWindowsMoveFromTitleBarOnly(ImGuiIO* self) { return self->ConfigWindowsMoveFromTitleBarOnly; }
void lyra_imgui_ImGuiIO_set_ConfigWindowsMoveFromTitleBarOnly(ImGuiIO* self, bool value) { self->ConfigWindowsMoveFromTitleBarOnly = value; }
bool lyra_imgui_ImGuiIO_get_ConfigWindowsCopyContentsWithCtrlC(ImGuiIO* self) { return self->ConfigWindowsCopyContentsWithCtrlC; }
void lyra_imgui_ImGuiIO_set_ConfigWindowsCopyContentsWithCtrlC(ImGuiIO* self, bool value) { self->ConfigWindowsCopyContentsWithCtrlC = value; }
bool lyra_imgui_ImGuiIO_get_ConfigScrollbarScrollByPage(ImGuiIO* self) { return self->ConfigScrollbarScrollByPage; }
void lyra_imgui_ImGuiIO_set_ConfigScrollbarScrollByPage(ImGuiIO* self, bool value) { self->ConfigScrollbarScrollByPage = value; }
bool lyra_imgui_ImGuiIO_get_ConfigIniSettingsSaveLastUsedDate(ImGuiIO* self) { return self->ConfigIniSettingsSaveLastUsedDate; }
void lyra_imgui_ImGuiIO_set_ConfigIniSettingsSaveLastUsedDate(ImGuiIO* self, bool value) { self->ConfigIniSettingsSaveLastUsedDate = value; }
int lyra_imgui_ImGuiIO_get_ConfigIniSettingsAutoDiscardMonths(ImGuiIO* self) { return self->ConfigIniSettingsAutoDiscardMonths; }
void lyra_imgui_ImGuiIO_set_ConfigIniSettingsAutoDiscardMonths(ImGuiIO* self, int value) { self->ConfigIniSettingsAutoDiscardMonths = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDebugIniSettings(ImGuiIO* self) { return self->ConfigDebugIniSettings; }
void lyra_imgui_ImGuiIO_set_ConfigDebugIniSettings(ImGuiIO* self, bool value) { self->ConfigDebugIniSettings = value; }
bool lyra_imgui_ImGuiIO_get_MouseDrawCursor(ImGuiIO* self) { return self->MouseDrawCursor; }
void lyra_imgui_ImGuiIO_set_MouseDrawCursor(ImGuiIO* self, bool value) { self->MouseDrawCursor = value; }
float lyra_imgui_ImGuiIO_get_ConfigMemoryCompactTimer(ImGuiIO* self) { return self->ConfigMemoryCompactTimer; }
void lyra_imgui_ImGuiIO_set_ConfigMemoryCompactTimer(ImGuiIO* self, float value) { self->ConfigMemoryCompactTimer = value; }
float lyra_imgui_ImGuiIO_get_MouseDoubleClickTime(ImGuiIO* self) { return self->MouseDoubleClickTime; }
void lyra_imgui_ImGuiIO_set_MouseDoubleClickTime(ImGuiIO* self, float value) { self->MouseDoubleClickTime = value; }
float lyra_imgui_ImGuiIO_get_MouseDoubleClickMaxDist(ImGuiIO* self) { return self->MouseDoubleClickMaxDist; }
void lyra_imgui_ImGuiIO_set_MouseDoubleClickMaxDist(ImGuiIO* self, float value) { self->MouseDoubleClickMaxDist = value; }
float lyra_imgui_ImGuiIO_get_MouseSingleClickDelay(ImGuiIO* self) { return self->MouseSingleClickDelay; }
void lyra_imgui_ImGuiIO_set_MouseSingleClickDelay(ImGuiIO* self, float value) { self->MouseSingleClickDelay = value; }
float lyra_imgui_ImGuiIO_get_MouseDragThreshold(ImGuiIO* self) { return self->MouseDragThreshold; }
void lyra_imgui_ImGuiIO_set_MouseDragThreshold(ImGuiIO* self, float value) { self->MouseDragThreshold = value; }
float lyra_imgui_ImGuiIO_get_KeyRepeatDelay(ImGuiIO* self) { return self->KeyRepeatDelay; }
void lyra_imgui_ImGuiIO_set_KeyRepeatDelay(ImGuiIO* self, float value) { self->KeyRepeatDelay = value; }
float lyra_imgui_ImGuiIO_get_KeyRepeatRate(ImGuiIO* self) { return self->KeyRepeatRate; }
void lyra_imgui_ImGuiIO_set_KeyRepeatRate(ImGuiIO* self, float value) { self->KeyRepeatRate = value; }
bool lyra_imgui_ImGuiIO_get_ConfigErrorRecovery(ImGuiIO* self) { return self->ConfigErrorRecovery; }
void lyra_imgui_ImGuiIO_set_ConfigErrorRecovery(ImGuiIO* self, bool value) { self->ConfigErrorRecovery = value; }
bool lyra_imgui_ImGuiIO_get_ConfigErrorRecoveryEnableAssert(ImGuiIO* self) { return self->ConfigErrorRecoveryEnableAssert; }
void lyra_imgui_ImGuiIO_set_ConfigErrorRecoveryEnableAssert(ImGuiIO* self, bool value) { self->ConfigErrorRecoveryEnableAssert = value; }
bool lyra_imgui_ImGuiIO_get_ConfigErrorRecoveryEnableDebugLog(ImGuiIO* self) { return self->ConfigErrorRecoveryEnableDebugLog; }
void lyra_imgui_ImGuiIO_set_ConfigErrorRecoveryEnableDebugLog(ImGuiIO* self, bool value) { self->ConfigErrorRecoveryEnableDebugLog = value; }
bool lyra_imgui_ImGuiIO_get_ConfigErrorRecoveryEnableTooltip(ImGuiIO* self) { return self->ConfigErrorRecoveryEnableTooltip; }
void lyra_imgui_ImGuiIO_set_ConfigErrorRecoveryEnableTooltip(ImGuiIO* self, bool value) { self->ConfigErrorRecoveryEnableTooltip = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDebugIsDebuggerPresent(ImGuiIO* self) { return self->ConfigDebugIsDebuggerPresent; }
void lyra_imgui_ImGuiIO_set_ConfigDebugIsDebuggerPresent(ImGuiIO* self, bool value) { self->ConfigDebugIsDebuggerPresent = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDebugHighlightIdConflicts(ImGuiIO* self) { return self->ConfigDebugHighlightIdConflicts; }
void lyra_imgui_ImGuiIO_set_ConfigDebugHighlightIdConflicts(ImGuiIO* self, bool value) { self->ConfigDebugHighlightIdConflicts = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDebugHighlightIdConflictsShowItemPicker(ImGuiIO* self) { return self->ConfigDebugHighlightIdConflictsShowItemPicker; }
void lyra_imgui_ImGuiIO_set_ConfigDebugHighlightIdConflictsShowItemPicker(ImGuiIO* self, bool value) { self->ConfigDebugHighlightIdConflictsShowItemPicker = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDebugBeginReturnValueOnce(ImGuiIO* self) { return self->ConfigDebugBeginReturnValueOnce; }
void lyra_imgui_ImGuiIO_set_ConfigDebugBeginReturnValueOnce(ImGuiIO* self, bool value) { self->ConfigDebugBeginReturnValueOnce = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDebugBeginReturnValueLoop(ImGuiIO* self) { return self->ConfigDebugBeginReturnValueLoop; }
void lyra_imgui_ImGuiIO_set_ConfigDebugBeginReturnValueLoop(ImGuiIO* self, bool value) { self->ConfigDebugBeginReturnValueLoop = value; }
bool lyra_imgui_ImGuiIO_get_ConfigDebugIgnoreFocusLoss(ImGuiIO* self) { return self->ConfigDebugIgnoreFocusLoss; }
void lyra_imgui_ImGuiIO_set_ConfigDebugIgnoreFocusLoss(ImGuiIO* self, bool value) { self->ConfigDebugIgnoreFocusLoss = value; }
const char* lyra_imgui_ImGuiIO_get_BackendPlatformName(ImGuiIO* self) { return self->BackendPlatformName; }
const char* lyra_imgui_ImGuiIO_get_BackendRendererName(ImGuiIO* self) { return self->BackendRendererName; }
bool lyra_imgui_ImGuiIO_get_WantCaptureMouse(ImGuiIO* self) { return self->WantCaptureMouse; }
void lyra_imgui_ImGuiIO_set_WantCaptureMouse(ImGuiIO* self, bool value) { self->WantCaptureMouse = value; }
bool lyra_imgui_ImGuiIO_get_WantCaptureKeyboard(ImGuiIO* self) { return self->WantCaptureKeyboard; }
void lyra_imgui_ImGuiIO_set_WantCaptureKeyboard(ImGuiIO* self, bool value) { self->WantCaptureKeyboard = value; }
bool lyra_imgui_ImGuiIO_get_WantTextInput(ImGuiIO* self) { return self->WantTextInput; }
void lyra_imgui_ImGuiIO_set_WantTextInput(ImGuiIO* self, bool value) { self->WantTextInput = value; }
bool lyra_imgui_ImGuiIO_get_WantSetMousePos(ImGuiIO* self) { return self->WantSetMousePos; }
void lyra_imgui_ImGuiIO_set_WantSetMousePos(ImGuiIO* self, bool value) { self->WantSetMousePos = value; }
bool lyra_imgui_ImGuiIO_get_WantSaveIniSettings(ImGuiIO* self) { return self->WantSaveIniSettings; }
void lyra_imgui_ImGuiIO_set_WantSaveIniSettings(ImGuiIO* self, bool value) { self->WantSaveIniSettings = value; }
bool lyra_imgui_ImGuiIO_get_NavActive(ImGuiIO* self) { return self->NavActive; }
void lyra_imgui_ImGuiIO_set_NavActive(ImGuiIO* self, bool value) { self->NavActive = value; }
bool lyra_imgui_ImGuiIO_get_NavVisible(ImGuiIO* self) { return self->NavVisible; }
void lyra_imgui_ImGuiIO_set_NavVisible(ImGuiIO* self, bool value) { self->NavVisible = value; }
float lyra_imgui_ImGuiIO_get_Framerate(ImGuiIO* self) { return self->Framerate; }
void lyra_imgui_ImGuiIO_set_Framerate(ImGuiIO* self, float value) { self->Framerate = value; }
int lyra_imgui_ImGuiIO_get_MetricsRenderVertices(ImGuiIO* self) { return self->MetricsRenderVertices; }
void lyra_imgui_ImGuiIO_set_MetricsRenderVertices(ImGuiIO* self, int value) { self->MetricsRenderVertices = value; }
int lyra_imgui_ImGuiIO_get_MetricsRenderIndices(ImGuiIO* self) { return self->MetricsRenderIndices; }
void lyra_imgui_ImGuiIO_set_MetricsRenderIndices(ImGuiIO* self, int value) { self->MetricsRenderIndices = value; }
int lyra_imgui_ImGuiIO_get_MetricsRenderWindows(ImGuiIO* self) { return self->MetricsRenderWindows; }
void lyra_imgui_ImGuiIO_set_MetricsRenderWindows(ImGuiIO* self, int value) { self->MetricsRenderWindows = value; }
int lyra_imgui_ImGuiIO_get_MetricsActiveWindows(ImGuiIO* self) { return self->MetricsActiveWindows; }
void lyra_imgui_ImGuiIO_set_MetricsActiveWindows(ImGuiIO* self, int value) { self->MetricsActiveWindows = value; }
ImVec2 lyra_imgui_ImGuiIO_get_MouseDelta(ImGuiIO* self) { return self->MouseDelta; }
void lyra_imgui_ImGuiIO_set_MouseDelta(ImGuiIO* self, ImVec2 value) { self->MouseDelta = value; }
ImGuiContext* lyra_imgui_ImGuiIO_get_Ctx(ImGuiIO* self) { return self->Ctx; }
ImVec2 lyra_imgui_ImGuiIO_get_MousePos(ImGuiIO* self) { return self->MousePos; }
void lyra_imgui_ImGuiIO_set_MousePos(ImGuiIO* self, ImVec2 value) { self->MousePos = value; }
bool lyra_imgui_ImGuiIO_get_MouseDown(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseDown) ? self->MouseDown[index] : bool(); }
void lyra_imgui_ImGuiIO_set_MouseDown(ImGuiIO* self, int index, bool value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseDown)) self->MouseDown[index] = value; }
float lyra_imgui_ImGuiIO_get_MouseWheel(ImGuiIO* self) { return self->MouseWheel; }
void lyra_imgui_ImGuiIO_set_MouseWheel(ImGuiIO* self, float value) { self->MouseWheel = value; }
float lyra_imgui_ImGuiIO_get_MouseWheelH(ImGuiIO* self) { return self->MouseWheelH; }
void lyra_imgui_ImGuiIO_set_MouseWheelH(ImGuiIO* self, float value) { self->MouseWheelH = value; }
ImGuiMouseSource lyra_imgui_ImGuiIO_get_MouseSource(ImGuiIO* self) { return self->MouseSource; }
void lyra_imgui_ImGuiIO_set_MouseSource(ImGuiIO* self, ImGuiMouseSource value) { self->MouseSource = value; }
ImGuiID lyra_imgui_ImGuiIO_get_MouseHoveredViewport(ImGuiIO* self) { return self->MouseHoveredViewport; }
void lyra_imgui_ImGuiIO_set_MouseHoveredViewport(ImGuiIO* self, ImGuiID value) { self->MouseHoveredViewport = value; }
bool lyra_imgui_ImGuiIO_get_KeyCtrl(ImGuiIO* self) { return self->KeyCtrl; }
void lyra_imgui_ImGuiIO_set_KeyCtrl(ImGuiIO* self, bool value) { self->KeyCtrl = value; }
bool lyra_imgui_ImGuiIO_get_KeyShift(ImGuiIO* self) { return self->KeyShift; }
void lyra_imgui_ImGuiIO_set_KeyShift(ImGuiIO* self, bool value) { self->KeyShift = value; }
bool lyra_imgui_ImGuiIO_get_KeyAlt(ImGuiIO* self) { return self->KeyAlt; }
void lyra_imgui_ImGuiIO_set_KeyAlt(ImGuiIO* self, bool value) { self->KeyAlt = value; }
bool lyra_imgui_ImGuiIO_get_KeySuper(ImGuiIO* self) { return self->KeySuper; }
void lyra_imgui_ImGuiIO_set_KeySuper(ImGuiIO* self, bool value) { self->KeySuper = value; }
ImGuiKeyChord lyra_imgui_ImGuiIO_get_KeyMods(ImGuiIO* self) { return self->KeyMods; }
void lyra_imgui_ImGuiIO_set_KeyMods(ImGuiIO* self, ImGuiKeyChord value) { self->KeyMods = value; }
bool lyra_imgui_ImGuiIO_get_WantCaptureMouseUnlessPopupClose(ImGuiIO* self) { return self->WantCaptureMouseUnlessPopupClose; }
void lyra_imgui_ImGuiIO_set_WantCaptureMouseUnlessPopupClose(ImGuiIO* self, bool value) { self->WantCaptureMouseUnlessPopupClose = value; }
ImVec2 lyra_imgui_ImGuiIO_get_MousePosPrev(ImGuiIO* self) { return self->MousePosPrev; }
void lyra_imgui_ImGuiIO_set_MousePosPrev(ImGuiIO* self, ImVec2 value) { self->MousePosPrev = value; }
ImVec2 lyra_imgui_ImGuiIO_get_MouseClickedPos(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseClickedPos) ? self->MouseClickedPos[index] : ImVec2(); }
void lyra_imgui_ImGuiIO_set_MouseClickedPos(ImGuiIO* self, int index, ImVec2 value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseClickedPos)) self->MouseClickedPos[index] = value; }
double lyra_imgui_ImGuiIO_get_MouseClickedTime(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseClickedTime) ? self->MouseClickedTime[index] : double(); }
void lyra_imgui_ImGuiIO_set_MouseClickedTime(ImGuiIO* self, int index, double value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseClickedTime)) self->MouseClickedTime[index] = value; }
bool lyra_imgui_ImGuiIO_get_MouseClicked(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseClicked) ? self->MouseClicked[index] : bool(); }
void lyra_imgui_ImGuiIO_set_MouseClicked(ImGuiIO* self, int index, bool value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseClicked)) self->MouseClicked[index] = value; }
bool lyra_imgui_ImGuiIO_get_MouseDoubleClicked(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseDoubleClicked) ? self->MouseDoubleClicked[index] : bool(); }
void lyra_imgui_ImGuiIO_set_MouseDoubleClicked(ImGuiIO* self, int index, bool value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseDoubleClicked)) self->MouseDoubleClicked[index] = value; }
ImU16 lyra_imgui_ImGuiIO_get_MouseClickedCount(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseClickedCount) ? self->MouseClickedCount[index] : ImU16(); }
void lyra_imgui_ImGuiIO_set_MouseClickedCount(ImGuiIO* self, int index, ImU16 value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseClickedCount)) self->MouseClickedCount[index] = value; }
ImU16 lyra_imgui_ImGuiIO_get_MouseClickedLastCount(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseClickedLastCount) ? self->MouseClickedLastCount[index] : ImU16(); }
void lyra_imgui_ImGuiIO_set_MouseClickedLastCount(ImGuiIO* self, int index, ImU16 value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseClickedLastCount)) self->MouseClickedLastCount[index] = value; }
bool lyra_imgui_ImGuiIO_get_MouseReleased(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseReleased) ? self->MouseReleased[index] : bool(); }
void lyra_imgui_ImGuiIO_set_MouseReleased(ImGuiIO* self, int index, bool value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseReleased)) self->MouseReleased[index] = value; }
double lyra_imgui_ImGuiIO_get_MouseReleasedTime(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseReleasedTime) ? self->MouseReleasedTime[index] : double(); }
void lyra_imgui_ImGuiIO_set_MouseReleasedTime(ImGuiIO* self, int index, double value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseReleasedTime)) self->MouseReleasedTime[index] = value; }
bool lyra_imgui_ImGuiIO_get_MouseDownOwned(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseDownOwned) ? self->MouseDownOwned[index] : bool(); }
void lyra_imgui_ImGuiIO_set_MouseDownOwned(ImGuiIO* self, int index, bool value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseDownOwned)) self->MouseDownOwned[index] = value; }
bool lyra_imgui_ImGuiIO_get_MouseDownOwnedUnlessPopupClose(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseDownOwnedUnlessPopupClose) ? self->MouseDownOwnedUnlessPopupClose[index] : bool(); }
void lyra_imgui_ImGuiIO_set_MouseDownOwnedUnlessPopupClose(ImGuiIO* self, int index, bool value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseDownOwnedUnlessPopupClose)) self->MouseDownOwnedUnlessPopupClose[index] = value; }
bool lyra_imgui_ImGuiIO_get_MouseWheelRequestAxisSwap(ImGuiIO* self) { return self->MouseWheelRequestAxisSwap; }
void lyra_imgui_ImGuiIO_set_MouseWheelRequestAxisSwap(ImGuiIO* self, bool value) { self->MouseWheelRequestAxisSwap = value; }
bool lyra_imgui_ImGuiIO_get_MouseCtrlLeftAsRightClick(ImGuiIO* self) { return self->MouseCtrlLeftAsRightClick; }
void lyra_imgui_ImGuiIO_set_MouseCtrlLeftAsRightClick(ImGuiIO* self, bool value) { self->MouseCtrlLeftAsRightClick = value; }
float lyra_imgui_ImGuiIO_get_MouseDownDuration(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseDownDuration) ? self->MouseDownDuration[index] : float(); }
void lyra_imgui_ImGuiIO_set_MouseDownDuration(ImGuiIO* self, int index, float value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseDownDuration)) self->MouseDownDuration[index] = value; }
float lyra_imgui_ImGuiIO_get_MouseDownDurationPrev(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseDownDurationPrev) ? self->MouseDownDurationPrev[index] : float(); }
void lyra_imgui_ImGuiIO_set_MouseDownDurationPrev(ImGuiIO* self, int index, float value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseDownDurationPrev)) self->MouseDownDurationPrev[index] = value; }
ImVec2 lyra_imgui_ImGuiIO_get_MouseDragMaxDistanceAbs(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseDragMaxDistanceAbs) ? self->MouseDragMaxDistanceAbs[index] : ImVec2(); }
void lyra_imgui_ImGuiIO_set_MouseDragMaxDistanceAbs(ImGuiIO* self, int index, ImVec2 value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseDragMaxDistanceAbs)) self->MouseDragMaxDistanceAbs[index] = value; }
float lyra_imgui_ImGuiIO_get_MouseDragMaxDistanceSqr(ImGuiIO* self, int index) { return index >= 0 && index < IM_ARRAYSIZE(self->MouseDragMaxDistanceSqr) ? self->MouseDragMaxDistanceSqr[index] : float(); }
void lyra_imgui_ImGuiIO_set_MouseDragMaxDistanceSqr(ImGuiIO* self, int index, float value) { if (index >= 0 && index < IM_ARRAYSIZE(self->MouseDragMaxDistanceSqr)) self->MouseDragMaxDistanceSqr[index] = value; }
float lyra_imgui_ImGuiIO_get_PenPressure(ImGuiIO* self) { return self->PenPressure; }
void lyra_imgui_ImGuiIO_set_PenPressure(ImGuiIO* self, float value) { self->PenPressure = value; }
bool lyra_imgui_ImGuiIO_get_AppFocusLost(ImGuiIO* self) { return self->AppFocusLost; }
void lyra_imgui_ImGuiIO_set_AppFocusLost(ImGuiIO* self, bool value) { self->AppFocusLost = value; }
bool lyra_imgui_ImGuiIO_get_AppAcceptingEvents(ImGuiIO* self) { return self->AppAcceptingEvents; }
void lyra_imgui_ImGuiIO_set_AppAcceptingEvents(ImGuiIO* self, bool value) { self->AppAcceptingEvents = value; }
ImWchar16 lyra_imgui_ImGuiIO_get_InputQueueSurrogate(ImGuiIO* self) { return self->InputQueueSurrogate; }
void lyra_imgui_ImGuiIO_set_InputQueueSurrogate(ImGuiIO* self, ImWchar16 value) { self->InputQueueSurrogate = value; }
ImGuiID lyra_imgui_ImGuiViewport_get_ID(ImGuiViewport* self) { return self->ID; }
void lyra_imgui_ImGuiViewport_set_ID(ImGuiViewport* self, ImGuiID value) { self->ID = value; }
ImGuiViewportFlags lyra_imgui_ImGuiViewport_get_Flags(ImGuiViewport* self) { return self->Flags; }
void lyra_imgui_ImGuiViewport_set_Flags(ImGuiViewport* self, ImGuiViewportFlags value) { self->Flags = value; }
ImVec2 lyra_imgui_ImGuiViewport_get_Pos(ImGuiViewport* self) { return self->Pos; }
void lyra_imgui_ImGuiViewport_set_Pos(ImGuiViewport* self, ImVec2 value) { self->Pos = value; }
ImVec2 lyra_imgui_ImGuiViewport_get_Size(ImGuiViewport* self) { return self->Size; }
void lyra_imgui_ImGuiViewport_set_Size(ImGuiViewport* self, ImVec2 value) { self->Size = value; }
ImVec2 lyra_imgui_ImGuiViewport_get_FramebufferScale(ImGuiViewport* self) { return self->FramebufferScale; }
void lyra_imgui_ImGuiViewport_set_FramebufferScale(ImGuiViewport* self, ImVec2 value) { self->FramebufferScale = value; }
ImVec2 lyra_imgui_ImGuiViewport_get_WorkPos(ImGuiViewport* self) { return self->WorkPos; }
void lyra_imgui_ImGuiViewport_set_WorkPos(ImGuiViewport* self, ImVec2 value) { self->WorkPos = value; }
ImVec2 lyra_imgui_ImGuiViewport_get_WorkSize(ImGuiViewport* self) { return self->WorkSize; }
void lyra_imgui_ImGuiViewport_set_WorkSize(ImGuiViewport* self, ImVec2 value) { self->WorkSize = value; }
float lyra_imgui_ImGuiViewport_get_DpiScale(ImGuiViewport* self) { return self->DpiScale; }
void lyra_imgui_ImGuiViewport_set_DpiScale(ImGuiViewport* self, float value) { self->DpiScale = value; }
ImGuiID lyra_imgui_ImGuiViewport_get_ParentViewportId(ImGuiViewport* self) { return self->ParentViewportId; }
void lyra_imgui_ImGuiViewport_set_ParentViewportId(ImGuiViewport* self, ImGuiID value) { self->ParentViewportId = value; }
ImGuiViewport* lyra_imgui_ImGuiViewport_get_ParentViewport(ImGuiViewport* self) { return self->ParentViewport; }
ImDrawData* lyra_imgui_ImGuiViewport_get_DrawData(ImGuiViewport* self) { return self->DrawData; }
bool lyra_imgui_ImGuiViewport_get_PlatformWindowCreated(ImGuiViewport* self) { return self->PlatformWindowCreated; }
void lyra_imgui_ImGuiViewport_set_PlatformWindowCreated(ImGuiViewport* self, bool value) { self->PlatformWindowCreated = value; }
bool lyra_imgui_ImGuiViewport_get_PlatformRequestMove(ImGuiViewport* self) { return self->PlatformRequestMove; }
void lyra_imgui_ImGuiViewport_set_PlatformRequestMove(ImGuiViewport* self, bool value) { self->PlatformRequestMove = value; }
bool lyra_imgui_ImGuiViewport_get_PlatformRequestResize(ImGuiViewport* self) { return self->PlatformRequestResize; }
void lyra_imgui_ImGuiViewport_set_PlatformRequestResize(ImGuiViewport* self, bool value) { self->PlatformRequestResize = value; }
bool lyra_imgui_ImGuiViewport_get_PlatformRequestClose(ImGuiViewport* self) { return self->PlatformRequestClose; }
void lyra_imgui_ImGuiViewport_set_PlatformRequestClose(ImGuiViewport* self, bool value) { self->PlatformRequestClose = value; }

}
